In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

df = pd.read_csv('../data/enhanced_student_habits_performance_dataset.csv')
print(df.shape)
df.head()

(80000, 31)

,student_id,age,gender,major,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,previous_gpa,semester,stress_level,dropout_risk,social_activity,screen_time,study_environment,access_to_tutoring,family_income_range,parental_support_level,motivation_level,exam_anxiety_score,learning_style,time_management_score,exam_score
0,100000,26,Male,Computer Science,7.645367,3.0,0.1,Yes,70.3,6.2,Poor,3,Some College,High,6.0,Yes,4.00,5,5.8,No,0,10.9,Co-Learning Group,Yes,High,9,7,8,Reading,3.0,100
1,100001,28,Male,Arts,5.700000,0.5,0.4,No,88.4,7.2,Good,4,PhD,Low,6.8,No,4.00,7,5.8,No,5,8.3,Co-Learning Group,Yes,Low,7,2,10,Reading,6.0,99
2,100002,17,Male,Arts,2.400000,4.2,0.7,No,82.1,9.2,Good,4,High School,Low,5.7,Yes,3.79,4,8.0,No,5,8.0,Library,Yes,High,3,9,6,Kinesthetic,7.6,98
3,100003,27,Other,Psychology,3.400000,4.6,2.3,Yes,79.3,4.2,Fair,3,Master,Medium,8.5,Yes,4.00,6,4.6,No,3,11.7,Co-Learning Group,Yes,Low,5,3,10,Reading,3.2,100
4,100004,25,Female,Business,4.700000,0.8,2.7,Yes,62.9,6.5,Good,6,PhD,Low,9.2,No,4.00,4,5.7,No,2,9.4,Quiet Room,Yes,Medium,9,1,10,Reading,7.1,98

In [3]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     80000 non-null  int64
 1   age                            80000 non-null  int64
 2   gender                         80000 non-null  str
 3   major                          80000 non-null  str
 4   study_hours_per_day            80000 non-null  float64
 5   social_media_hours             80000 non-null  float64
 6   netflix_hours                  80000 non-null  float64
 7   part_time_job                  80000 non-null  str
 8   attendance_percentage          80000 non-null  float64
 9   sleep_hours                    80000 non-null  float64
 10  diet_quality                   80000 non-null  str
 11  exercise_frequency             80000 non-null  int64
 12  parental_education_level       80000 non-null  str
 13  internet_quality               80000 non-null  str
 14  mental_health_rating           80000 non-null  float64
 15  extracurricular_participation  80000 non-null  str
 16  previous_gpa                   80000 non-null  float64
 17  semester                       80000 non-null  int64
 18  stress_level                   80000 non-null  float64
 19  dropout_risk                   80000 non-null  str
 20  social_activity                80000 non-null  int64
 21  screen_time                    80000 non-null  float64
 22  study_environment              80000 non-null  str
 23  access_to_tutoring             80000 non-null  str
 24  family_income_range            80000 non-null  str
 25  parental_support_level         80000 non-null  int64
 26  motivation_level               80000 non-null  int64
 27  exam_anxiety_score             80000 non-null  int64
 28  learning_style                 80000 non-null  str
 29  time_management_score          80000 non-null  float64
 30  exam_score                     80000 non-null  int64
dtypes: float64(10), int64(9), str(12)
memory usage: 18.9 MB

student_id                       0
age                              0
gender                           0
major                            0
study_hours_per_day              0
social_media_hours               0
netflix_hours                    0
part_time_job                    0
attendance_percentage            0
sleep_hours                      0
diet_quality                     0
exercise_frequency               0
parental_education_level         0
internet_quality                 0
mental_health_rating             0
extracurricular_participation    0
previous_gpa                     0
semester                         0
stress_level                     0
dropout_risk                     0
social_activity                  0
screen_time                      0
study_environment                0
access_to_tutoring               0
family_income_range              0
parental_support_level           0
motivation_level                 0
exam_anxiety_score               0
learning_style                   0
time_management_score            0
exam_score                       0
dtype: int64

In [4]:
df.describe()

,student_id,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating,previous_gpa,semester,stress_level,social_activity,screen_time,parental_support_level,motivation_level,exam_anxiety_score,time_management_score,exam_score
count,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000
mean,139999.500000,22.004288,4.174388,2.501366,1.997754,69.967884,7.017418,3.516587,6.804108,3.602448,4.497338,5.012478,2.500225,9.673029,5.479438,5.488525,8.508475,5.499132,89.141350
std,23094.155105,3.745570,2.004135,1.445441,1.155992,17.333015,1.467377,2.291575,1.921579,0.462876,2.295312,1.953174,1.704292,2.780869,2.873327,2.867782,1.796411,2.603534,11.591497
min,100000.000000,16.000000,0.000000,0.000000,0.000000,40.000000,4.000000,0.000000,1.000000,1.640000,1.000000,1.000000,0.000000,0.300000,1.000000,1.000000,5.000000,1.000000,36.000000
25%,119999.750000,19.000000,2.800000,1.200000,1.000000,55.000000,6.000000,2.000000,5.500000,3.270000,2.000000,3.600000,1.000000,7.800000,3.000000,3.000000,7.000000,3.200000,82.000000
50%,139999.500000,22.000000,4.125624,2.500000,2.000000,69.900000,7.000000,4.000000,6.900000,3.790000,5.000000,5.000000,2.000000,9.700000,5.000000,5.000000,10.000000,5.500000,93.000000
75%,159999.250000,25.000000,5.500000,3.800000,3.000000,84.900000,8.000000,6.000000,8.200000,4.000000,7.000000,6.400000,4.000000,11.600000,8.000000,8.000000,10.000000,7.800000,100.000000
max,179999.000000,28.000000,12.000000,5.000000,4.000000,100.000000,12.000000,7.000000,10.000000,4.000000,8.000000,10.000000,5.000000,21.000000,10.000000,10.000000,10.000000,10.000000,100.000000

In [5]:
cat_cols = ['gender', 'major', 'part_time_job', 'diet_quality', 'parental_education_level',
               'internet_quality', 'extracurricular_participation', 'dropout_risk',
               'study_environment', 'access_to_tutoring', 'family_income_range', 'learning_style']
for col in cat_cols:
    print(col, '->', df[col].unique())

gender -> <StringArray>
['Male', 'Other', 'Female']
Length: 3, dtype: str
major -> <StringArray>
['Computer Science', 'Arts', 'Psychology', 'Business', 'Engineering',
 'Biology']
Length: 6, dtype: str
part_time_job -> <StringArray>
['Yes', 'No']
Length: 2, dtype: str
diet_quality -> <StringArray>
['Poor', 'Good', 'Fair']
Length: 3, dtype: str
parental_education_level -> <StringArray>
['Some College', 'PhD', 'High School', 'Master', 'Bachelor']
Length: 5, dtype: str
internet_quality -> <StringArray>
['High', 'Low', 'Medium']
Length: 3, dtype: str
extracurricular_participation -> <StringArray>
['Yes', 'No']
Length: 2, dtype: str
dropout_risk -> <StringArray>
['No', 'Yes']
Length: 2, dtype: str
study_environment -> <StringArray>
['Co-Learning Group', 'Library', 'Quiet Room', 'Dorm', 'Cafe']
Length: 5, dtype: str
access_to_tutoring -> <StringArray>
['Yes', 'No']
Length: 2, dtype: str
family_income_range -> <StringArray>
['High', 'Low', 'Medium']
Length: 3, dtype: str
learning_style -> <StringArray>
['Reading', 'Kinesthetic', 'Visual', 'Auditory']
Length: 4, dtype: str

In [6]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate student_ids:", df['student_id'].duplicated().sum())

Duplicate rows: 0
Duplicate student_ids: 0

In [7]:
df[['study_hours_per_day','sleep_hours','exam_score','attendance_percentage','previous_gpa']].describe()

,study_hours_per_day,sleep_hours,exam_score,attendance_percentage,previous_gpa
count,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000
mean,4.174388,7.017418,89.141350,69.967884,3.602448
std,2.004135,1.467377,11.591497,17.333015,0.462876
min,0.000000,4.000000,36.000000,40.000000,1.640000
25%,2.800000,6.000000,82.000000,55.000000,3.270000
50%,4.125624,7.000000,93.000000,69.900000,3.790000
75%,5.500000,8.000000,100.000000,84.900000,4.000000
max,12.000000,12.000000,100.000000,100.000000,4.000000